# Tensorflow2.0 小练习

In [1]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [5]:
def softmax(x):
    # 计算指数
    exp_x = tf.exp(x)
    # 对最后一维求和
    sum_exp_x = tf.reduce_sum(exp_x, axis=-1, keepdims=True)
    # 计算概率
    prob_x = exp_x / sum_exp_x
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [6]:
def sigmoid(x):
    # 实现 sigmoid 公式：1/(1+e^(-x))
    prob_x = 1 / (1 + tf.exp(-x))
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [7]:
def softmax_ce(x, label):
    eps = 1e-12
    x = np.clip(x, eps, 1 - eps)  # 限制 x 在 [eps, 1-eps] 避免数值问题
    loss = -np.sum(label * np.log(x), axis=-1)  # 对类别维度求和
    return np.mean(loss)  # 对样本维度求平均

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

np.True_

## 实现 sigmoid 交叉熵loss函数

In [8]:
def sigmoid_ce(x, label):
    eps = 1e-12  # 添加小值避免 log(0)
    x = np.clip(x, eps, 1 - eps)  # 限制 x 在 [eps, 1-eps] 避免数值问题
    loss = -(label * np.log(x) + (1 - label) * np.log(1 - x))
    return np.mean(loss)  # 对样本取平均

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[1. 0. 0. 1. 0. 0. 1. 0. 0. 1.]


np.True_